declare const _default: {
    length: number;
    toString(): string;
    toLocaleString(): string;
    pop(): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any> | undefined;
    push(...items: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]): number;
    concat(...items: ConcatArray<import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>[]): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    concat(...items: (import("vue").ComponentOptions<{}, any, any, any, any, any, any, any> | ConcatArray<import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>)[]): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    join(separator?: string | undefined): string;
    reverse(): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    shift(): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any> | undefined;
    slice(start?: number | undefined, end?: number | undefined): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    sort(compareFn?: ((a: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, b: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>) => number) | undefined): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    splice(start: number, deleteCount?: number | undefined): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    splice(start: number, deleteCount: number, ...items: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    unshift(...items: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]): number;
    indexOf(searchElement: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, fromIndex?: number | undefined): number;
    lastIndexOf(searchElement: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, fromIndex?: number | undefined): number;
    every<S extends import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => value is S, thisArg?: any): this is S[];
    every(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => unknown, thisArg?: any): boolean;
    some(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => unknown, thisArg?: any): boolean;
    forEach(callbackfn: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => void, thisArg?: any): void;
    map<U>(callbackfn: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => U, thisArg?: any): U[];
    filter<S_1 extends import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => value is S_1, thisArg?: any): S_1[];
    filter(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => unknown, thisArg?: any): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    reduce(callbackfn: (previousValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>;
    reduce(callbackfn: (previousValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, initialValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>;
    reduce<U_1>(callbackfn: (previousValue: U_1, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => U_1, initialValue: U_1): U_1;
    reduceRight(callbackfn: (previousValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>;
    reduceRight(callbackfn: (previousValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, initialValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>;
    reduceRight<U_2>(callbackfn: (previousValue: U_2, currentValue: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, currentIndex: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => U_2, initialValue: U_2): U_2;
    find<S_2 extends import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>(predicate: (this: void, value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, obj: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => value is S_2, thisArg?: any): S_2 | undefined;
    find(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, obj: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => unknown, thisArg?: any): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any> | undefined;
    findIndex(predicate: (value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, obj: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => unknown, thisArg?: any): number;
    fill(value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, start?: number | undefined, end?: number | undefined): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    copyWithin(target: number, start: number, end?: number | undefined): import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[];
    entries(): IterableIterator<[number, import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>]>;
    keys(): IterableIterator<number>;
    values(): IterableIterator<import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>;
    includes(searchElement: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, fromIndex?: number | undefined): boolean;
    flatMap<U_3, This = undefined>(callback: (this: This, value: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>, index: number, array: import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>[]) => U_3 | readonly U_3[], thisArg?: This | undefined): U_3[];
    flat<A, D extends number = 1>(this: A, depth?: D | undefined): FlatArray<A, D>[];
    [Symbol.iterator](): IterableIterator<import("vue").ComponentOptions<{}, any, any, any, any, any, any, any>>;
    [Symbol.unscopables](): {
        copyWithin: boolean;
        entries: boolean;
        fill: boolean;
        find: boolean;
        findIndex: boolean;
        keys: boolean;
        values: boolean;
    };
    install: (Vue: any, opts?: {}) => void;
};
export default _default;
